version: '3'

services:
  ftp:
    build: ./ftp-test
    image: ftp-test
    restart: always
    ports:
      - "2020-2021:2020-2021"
      - "64000-64999:64000-64999"

  mongo:
    image: mongo:4.2-bionic
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: dba
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - "$PWD/mongo-entrypoint/:/docker-entrypoint-initdb.d/"

volumes:
  mongovolume: {}
